### PR TITLE
Add additional check to not SIGSEV when filenames are invalid in the fil...

### PR DESCRIPTION
**Pull request by centic9**
...elist.txt. Also fix some compiler warnings. 

Saw this when having a wrong filename in filelist.txt during replacing audio files in gme files.

### CODE REVIEW

**Comment by nomeata** [comment]
Oh well, if @SuSonicTH  does not mind I’ll simply merge this, and make @centic9  responsible for any future breakage of the C code :-)

**Comment by SuSonicTH** [comment]
I don't mind at all!

Cheers,
Michael


Joachim Breitner <notifications@github.com> schrieb am Tue Feb 24 2015 at
11:22:09 AM:

**Comment by nomeata** [comment]
Ah, great to hear that; I wasn’t sure if you were following this any more.

**Comment by SuSonicTH** [comment]
I'm following the project, even subscribed to the mailing list but
unfortunately I have no time do develop something myself.

Joachim Breitner <notifications@github.com> schrieb am Tue Feb 24 2015 at
12:55:13 PM:

**Comment by centic9** [comment]
sure, blame me :)

**Pull request merged**
