### PR TITLE
Add ogg2gme.py wrapper script around tttool.

### PR DESCRIPTION
**Pull request by jovermann**
Outline:
ogg2gme.py is a Python script which allows users which are
unfamiliar with tttool, oids and the *.yaml files to produce
*.gme files and *.png files containing OID labels. All one
needs to do is:
- record *.ogg files into a specifically named directory
- double click a *.bat file on Windows (or invoke ogg2gme.py on Linux)
- copy the generated *.gme file onto the stick
- print the OID labels (*.png file)

The script produces a simple 1:1 mapping from *.ogg files to OIDs.
This is sufficient to add Tip-Toi support to non-Tip-Toi books and
to produce speaking labels for anything.

The generated *.yaml file can be manually modified any time (for
example using more complicated mechanisms like registers). The
modifications are preserved across ogg2gme.py invocations.

See ogg2gme/README.txt for details (German).

### CODE REVIEW

**Comment by nomeata** [comment]
Hi.

Interesting approach to allowing people to quickly create something. The idea is definitely good!

I am however reluctant to merge this. I don’t think the users are best serve if they have to make decisions about what tools to use, and have to deal with various abstraction layers. If the tttool is not good enough, then it should be improved!

At least for the windows user, a suitable interface could be a directory consisting of ogg files, as you suggest, which the user would drag onto `tttool.exe` to trigger processing, i.e. produce the oid table (if something has changes) and the gme files.

But if the text interface to tttool is not easy enough for many users, then maybe it is time to create a small GUI instead?

**Comment by jovermann** [comment]
Hi,

I fully agree with your concerns regarding wrappers and scripts. I am afraid, this is because I am totally unable to program this functionality in Haskell. :-) Having this functionality inside tttool would be brilliant. Having a very simple GUI would be even better of course. I will probably never be able to do this, so this pull request should transport the idea. Maybe someone else finds the time to write a GUI.

If you would write a GUI around tttool, what would you recommend to use? Does Haskell support producing GUIs?

My goal was to produce a package which I can 'install' on friends Windows machines so they can 'record stuff on their Tip-Toi' too. The minimum flow is really to associate one sound file with one OID and this is what a lot of people would love to have I assume. The pens which can do this (AnyBook) are out of stock since more than a year now and people get desperate. The AnyBook pens cost around 90 EUR which we would have immediately paid. 

The niche market for such recording pens is for example for handicapped children which cannot read for whatever reason, but which still love childrens books, like Jim Knopf. We are currently adding the story text to a couple of childrens books for our son (4 years, down syndrome) as a surprise for Christmas. He absolutely loves Tip-Toi and spends hours over the Ravensburger books. But he also loves to look at other books and listen to the stories.

**Comment by nomeata** [comment]
> I am afraid, this is because I am totally unable to program this functionality in Haskell. :-)

It’s fun learning! But even if not, it is already a great help to design and think certain features through, and help with testing, even if you do not contribute code. Coding is just one bit of the work :-)

A python prototype is of course a great way to explain what you want, but I feel a bit bad if you put in so much work in the implementation without it being used.

For discussion of such features, I suggest to do it on the mailing lists, where more people can throw in ideas.

> If you would write a GUI around tttool, what would you recommend to use? Does Haskell support producing GUIs?

Of course it does, despite the impression some people get from university, Haskell is a general purpose programming language. Besides maybe programming a OS kernel, everything can be done in Haskell :-)

There are bindings to GTK and Qt, although maybe something more modern, like reflex-dom, would work better. This way, the same program can either run in the browser, or locally as a regular program, but still using web technologies (Webkit) to take care of the UI.

> My goal was to produce a package which I can 'install' on friends Windows machines so they can 'record stuff on their Tip-Toi' too. The minimum flow is really to associate one sound file with one OID and this is what a lot of people would love to have I assume.

Yes, that’s a good point. I wonder how feasible it would be to compiler tttool to JavaScript (you can do that with Haskell), add a simple HTML page where you can add a few audio files, and get out the required GME and PDF files. This way, nothing needs to be installed and everyone can use a browser these days. And browsers can probably even record audio these days...

Might be a bit tricky, though, to save the intermediate states, and a tad slow. A proper web service would work better, but that would require server resources for storage, and more maintenance.

BTW, I am not at all opposed to people writing programs or scripts that wrap tttool; i.e. someone could easily write a web service that just runs `tttool` as it is on the server, and of course use what ever language he wants to use. Similarly, it could make sense for you to distribute your tool as a separate project. I just don’t want this repository to become cluttered lose focus.

**Comment by stgermain1** [comment]
Some Time Ago (approx 1 years) , there exists an Java-Frontend (TipDev) made by german Students: 

https://youtu.be/Jhf5XewcZGI?t=28

https://youtu.be/KevR8ZjDLB4?t=122

https://youtu.be/Jhf5XewcZGI?t=248

**Comment by uli42** [comment]
On Tue, Nov 3, 2015 at 10:11 AM, st germain <notifications@github.com> wrote:
>
> Some Time Ago (approx 1 years) , there exists an Java-Frontend (TipDev) made by german Students:
>
> https://youtu.be/Jhf5XewcZGI?t=28
>
> https://youtu.be/KevR8ZjDLB4?t=122
>
> https://youtu.be/Jhf5XewcZGI?t=248

This has been an Austrian project and someone here already had
contacted them. The system does not exist anymore and was only running
on (or when connected to?) an Ravensburger server.

Uli

**Pull request closed without merging**
